apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: rabbitmq
    targetRevision: 15.0.6
    helm:
      values: |
        auth:
          username: rabbitmq
          existingPasswordSecret: rabbitmq-creds
          existingPasswordSecretKey: rabbitmq-password
          existingErlangSecret: rabbitmq-creds
          existingErlangSecretKey: rabbitmq-erlang-cookie
        persistence:
          enabled: true
          size: 8Gi
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
