apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-creds
  namespace: database
spec:
  encryptedData:
    rabbitmq-erlang-cookie: AgCF+vtZte6KPO5s0fcf1ZE4cECYVvmzB5PolGemT/8qsB0LMpyQ0YPuNlfHfVYj+iqe2fCZudfD05pOAotsSFT45YPpPFrLirKH796WWMs3ksQoqAmgSDBq5yZvUIg4rOI+DWS7Oi1dzkjq3/vssHC4WlU/YNWjPZEMHT2/Q4Lm+IWM9+1ZOVUuYVG7Ul9ZUuKaaT0lk7eXEL9Wq2vJkGWfgWj3aAtsmz7vAlcB6anfN1ptqMgrXbu5rohfJhmS6j8tghYtDzmZGXxyitodrm95TFiS8OgXW7EXdUA+0jZy8jJ1c07p8348x+Ly3pzrTiUSyfHl1vSKu1+mzep1T/9CFbjr91tyoCGE5qpke89S3hoJYbHX2XXnv3AerUW05lqBCNoJiWAaUPBpbks2az6NI8wx5K0b4v/JFk0zyWdIbPa44agbM0WmxQxkO9gV29YCxSqqt0HsN1fYk6BrnQS/PJ+Mz9oIhg2Id1BtC7adoESwKH8P7BgxG4JZBmV0/csjihbsqtL6TFalo66v413AmkmCZuSmh7SZ1GF8laVwQkKfkLW+uYZcTQzE3thmhfWHO8irFyKDVXjaTu7ZCjMCRc8aALqgAnfM4UohL6MVmR/bwJwQ5OyuGpnS65XIU4845HChjyqreXGBPlPdt+9gpcY+8cvcc5058w7igBzyWlDK/mguRLxN9Lmao9Ra3W669VEb15Ww5zxzd/DdTEnuPM8JKNH/ZYkF5g==
    rabbitmq-password: AgBNhVTGPgrP04MzVSOUq3QOPgRnUE/jiwdRf/vSz/xl1o7QnLXei5T57tj3BjFrN6BmD33WclZw3X7VZayS2ltWGq/MloYr9SRDy+f+zqQk0kYQ4kOCHe80KhAK25IRn43uxou8Kk2s/w2YQOhvdNo3Sf0fjKP3ycB44D1VXUIT3AFvoGJX/YVwcktyU+IEJAMsZGPIo4jkIryy72PdFC9aJPQviPvKcVpt711cH5TijmiTKo4mffuGvVrxuPDmkYXbw+59LWT4CD9tfSSDQcvHnd5G4ekBCq8siFB1jO6s3QHxCYvg1puiu3k+Z5L8tzAYpkNanzsBQRbIfmxq5WXjwiLt6SdJT5Q5XUQqHB0wBT5ZnHZ2U3jUklhoO8viNmoccHWF1E6zGvT5JXGZnH/HPsbWu+L9SPvoTFZDCw4Q9IHmsnW9radlJhsiRt8ffpSFwrXPxkm6CN1tsFTaYw1nVqwN761IkMxtH89vCqg/9KavVTIX8pngJ7kQklSo8PfY0p03yk/Zw9KsZCD3m1x9PGq9DYSv+JpjhbwM9u53G1Hq9zzxALx6jUZ6s/dmsdEZLGdpcRNDA+m42j5Sf/WIHn4jzUgUFCF/30zX6JF25csZZB1numxAfC/G91cC1QVAmOAUEe2TdfhM/SKZKkKeXq/NzdhkFMbQLq2JerfAd4qzAoXyse9hwxWJJX5Tun0WorGbraNlGsCQNT2zzw==
  template:
    metadata:
      name: rabbitmq-creds
      namespace: database
    type: Opaque
