apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data
  labels:
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/instance: minecraft
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
