adminUser: admin
adminPassword: admin123   # TEMPORARY – we’ll secure this next

admin:
  existingSecret: grafana-admin
  userKey: admin-user
  passwordKey: admin-password

persistence:
  enabled: true
  storageClassName: local-path
  size: 5Gi

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - grafana.felipemalacarne.com.br
  path: /
  pathType: Prefix
  tls:
    - secretName: grafana-tls
      hosts:
        - grafana.felipemalacarne.com.br

service:
  port: 80

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://monitoring-prometheus-kube-prometheus.monitoring:9090
        access: proxy
        isDefault: true

dashboards:
  kubernetes:
    cluster:
      file: dashboards/kubernetes/cluster.json
    nodes:
      file: dashboards/kubernetes/nodes.json
    pods:
      file: dashboards/kubernetes/pods.json

  system:
    node-exporter:
      file: dashboards/system/node-exporter.json

dashboardsConfigMaps:
  kubernetes:
    grafana_folder: Kubernetes
  system:
    grafana_folder: System
