admin:
  existingSecret: grafana-admin
  userKey: admin-user
  passwordKey: admin-password

persistence:
  enabled: true
  storageClassName: local-path
  size: 5Gi

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  hosts:
    - grafana.felipemalacarne.com.br
  path: /
  pathType: Prefix
  tls:
    - secretName: grafana-tls
      hosts:
        - grafana.felipemalacarne.com.br

service:
  port: 80

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-kube-prometheus-prometheus.monitoring:9090
        access: proxy
        isDefault: true

sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "1"
