apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-creds
  namespace: database
spec:
  encryptedData:
    postgres-password: AgCXPVCa7brAbmSZgbmurQg4AtQqKp0NUHbpS1GeH7edrLjDOu0UhXgaaO3msqOJyMPeEfuq2XLfgWCcQkkcijQuYQ3hiUja/BnvcFsgZnoe6sDzC4YGcXdYdqF7rXqehnDSBS7wgfV6zfSV92ATNBHUvFUD7NmT6WZKheAJyA36Fa34u6AP7PQkvg40mGkN8hUUoe8bBPVGTvrJ4SXhF5JHdK/liM4Yp7gZ4xTzw2p0gWt441Soo3Ipp+v6Vua+zEZP/iZmDNlNu9/cwbTawOCLVFXOtSXcdkb2skvEntVfhIWwL8ReYZLPstBmY93n9XgxMUDoZMr2zRk6EVdh7x85gbcoGql3PFgoW69BfRKg20jj75VHRIRCcrXRa62r1uSFVQmrbzjf2giXPFWzhQew4F+sivbTTz3AI1F7HgRzuxWgIHCkg5C0GdxYN05SB3RBZixCOfzSwvxm9RILXQq3Bg9DsMWsp3Hi9T1iStQmma5dkCMTWuqznYmADFo6OTCEw1MMbo6a4k2mEAcDwMhHBNgJPIGSWnmGXTUs0eKMPo4aj4rzFEJHzQlxQeF2LfI3EW/GxQy+WYKXQRKjxcvsgeLRweYH3URfilV65kEDp4+NJrMon0JlTj2bYRBdjbor8pgb3pldGoEwOkdupX6sucIvlx8zgsS9YwsUVmc10P7MnJOoISxgYC6TkVuwf7QbqrmfoOU21/BefY2Z9w==
  template:
    metadata:
      name: postgres-creds
      namespace: database
