---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-postgres-creds
  namespace: n8n
spec:
  encryptedData:
    password: AgBW94msopMbuEdg5AkSwGqygYqlb534+RxiIRwVsDwAHGT82X12f5rz5nOi9meMqadUHmn9VJYdSWjJU4ODnj05hR46UEsraw8dVwJzL1GLMrOXi0/NfcI9pGbN82vRnSmYFLfhAsFp+YRWQOERArlo/elHlezBjncHGBX6cvYUtWSx+gdagMHvr70ZUfVnAb32tzSIjdArAf9WRJUalk7WTNeqjp414fDSVafgXPcOYCxJZYj/yjhRXFhPDwnQFZqGyopjPsxp+4IfgVcDdVf6S2B/RECz1GcmxEe/X2sSqwpI4evhH8zGae3vejuxFYdl5lkBD17SmlsvK8fu16159FeSTZmFjxQdZFgaf8RMubLzhwp05dP8bfT00nBsOwGnWnQsoUnsrd9gMd5kvZP8A+vAePF7wLYfsFPUANNvoacveYVu3HyKZizrGLtocCjbZR8yaOyccernQEd07qGDx3scbaIR2KXbJqdkC5+48dBKp/xIvwJJgbMH7BkZDAyPVrq42ns9h+ctbMsULYB72tTTPVreSKFcHa9tNxJ9pq+XrZx+6gi/2veCGAQBpYLSwwbUNkPX4a0NvDrJwjWo5NR0zBLydqjd/XkAsDYsPR2VyWh83WS0sLhvEHboZnvMcWj1obdjS4ARsVipCHtyAVOETtRXli8iEzVFnrhqMgERkVKoZ+iCo9ICocEJKX/SlcBTF8pgck3epZaBTQ==
    username: AgCqGfwJhVwM5AvrM6F59SS1wcKtppMS7fbIrrvxaSWwKbVhLfUSXm9Pp1zam8t3TovCnm5TWmC3h9B01AJMsth0+72UZhjQOy/gtorNGvzo812plDVfbusPOHfkgp0k1W7yV8JY0sFmvOQgMX2LTMIL6o7NvkLWdIFb8hBjB70RmWvZUdfSdxq+R0Qs2DUQ80UV1/hLJUXxS5FWHvtBK1DLgKeVqqG7eqPx5OprSC1wTDN7CfCG6L1e55VB8an1GIvUG9VLUHmfFNdTdYkRvJR/boyH1LTwg5I4WKY8qAsUx0rnxllDnUVrs6IYC2p6KohgVZVyftsX/8wUTvzBQGIx8vBpnc6XIoI1N6ChPoUiplEvTND1aoi1vNWJmi091n64OkpaFDdbLSvSQaR8nKX54LTelMYHj6LV4NHT2zwr2Ny2UzckQ75afM0gF5AiB3ZDWL+FwZbSlt9EvTpKZ2L5PRg3y/ghvI0kUB3pfcPois7ekxtqLeH8FqK4ipWX9tbVRnHFqwqiknIx1RdV4CYsM1sf3ylE9qSVE+L5+w++Ebtsr5e7FJOaNM32YEvgew83bfoLX7J45OfKai14C4K6Ud4qQeNOo/0dYu5SMDNBs9eVl7uH+FbR3IEpC64dlL19a0ShkiSyEoeTAyw+SHsW3rLvvnPGFR2vNn1PPPntuD2cn4sMHEwZpTYJLjVSYoxEGQ0=
  template:
    metadata:
      name: n8n-postgres-creds
      namespace: n8n
